name: ci (tests + coverage)

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    # 👇 fa que els job-runs amb experimental=true no facin fallar el workflow
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        experimental: [false]
        include:
          - node: 24
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps (clean)
        run: npm ci

      - name: Run tests + coverage (Vitest)
        run: npm run test:cov

      - name: Upload coverage HTML (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node${{ matrix.node }}
          path: coverage
          if-no-files-found: ignore
