name: version (auto on push)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # per commitejar/push i crear tags

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # 1) Si hi ha changesets pendents, fa el bump i genera CHANGELOG
      - name: Version packages if pending changesets
        id: version
        run: |
          if ls .changeset/*.md >/dev/null 2>&1; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
            npx changeset version
          else
            echo "has_changesets=false" >> $GITHUB_OUTPUT
          fi

      # 2) Commit & push del bump (evitem bucle amb [skip ci])
      - name: Commit & push version bump
        if: steps.version.outputs.has_changesets == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: version packages [skip ci]"
          git push

      # 3) (Opcional) Crear etiqueta git segons package.json
      - name: Tag version
        if: steps.version.outputs.has_changesets == 'true'
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          git tag "v${PKG_VERSION}"
          git push --tags

      # 4) (Opcional) Crear GitHub Release amb l'etiqueta
      - name: Create GitHub Release
        if: steps.version.outputs.has_changesets == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.pkg_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
